TavernofSoul/Items/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:id>', views.item_detail, name='item'),
]

TavernofSoul/Jobs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.item_detail, name='jobs'),
]

TavernofSoul/Maps/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:id>', views.item_detail, name='maps'),
]

TavernofSoul/Market/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
]

if settings.REGION=='test':
    urlpatterns = [
        path('', views.index, name = 'market'),
        path('postMarket', csrf_exempt(views.post), name = 'postMarket'),
    ]    

TavernofSoul/Monsters/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.item_detail, name='monster'),
]

TavernofSoul/TavernofSoul/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap # new
from Attributes.models import Attributes
from Buffs.models import Buffs
from Items.models import Items
from Jobs.models import Jobs
from Skills.models import Skills
from Maps.models import Maps
from django.contrib.sitemaps import Sitemap
from django.shortcuts import reverse
class StaticViewSitemap(Sitemap):
    def items(self):
        return ['Dashboard:index', 
            'Items:index', 
            'Skills:index', 
            'Buffs:index', 
            'Jobs:index',
            'Attributes:index',
            'Planner:index',
            'Other:achieve'
            ]
    def location(self, item):
        return reverse(item)

sitemaps = {
    'static'     : StaticViewSitemap,
    "attributes" : GenericSitemap({'queryset' : Attributes.objects.all()}),
    "buffs"      : GenericSitemap({'queryset' : Buffs.objects.all()}),
    "items"      : GenericSitemap({'queryset' : Items.objects.all()}),
    "jobs"       : GenericSitemap({'queryset' : Jobs.objects.all()}),
    "maps"       : GenericSitemap({'queryset' : Maps.objects.all()}),
    "skills"     : GenericSitemap({'queryset' : Skills.objects.all()}),


}

urlpatterns = [
    path('', include(('Dashboard.urls',"Dashboard"),namespace = "Dashboard")),    
    path('items/', include(('Items.urls',"Items"),namespace = "Items")),   
    path('monsters/', include(('Monsters.urls',"Monsters"),namespace = "Monsters")), 
    path('maps/', include(('Maps.urls',"Maps"),namespace = "Maps")), 
    path('jobs/', include(('Jobs.urls',"Jobs"),namespace = "Jobs")), 
    path('skills/', include(('Skills.urls',"Skills"),namespace = "Skills")), 
    path('attributes/', include(('Attributes.urls',"Attributes"),namespace = "Attributes")), 
    path('buffs/', include(('Buffs.urls',"Buffs"),namespace = "Buffs")), 
    path('planner/', include(('Planner.urls',"Planner"),namespace = "Planner")), 
    path('other/', include(('Other.urls',"Other"),namespace = "Other")), 
    #path('changes/', include(('ipfparser.urls',"Parser"),namespace = "Parser")), 
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TavernofSoul/Items/models.py
from django.db import models
from django_mysql.models import ListCharField
from Skills.models import Skills
from django.urls import reverse
# Create your models here.

class Items (models.Model):
    ids         = models.CharField(max_length = 30, db_index=True)
    id_name         = models.CharField(max_length = 100, db_index=True)
    cooldown        = models.IntegerField(default=None, blank=True, null=True) 
    descriptions    = models.TextField(default=None, blank=True, null=True) 
    name            = models.CharField(max_length = 200,default=None, blank=True, null=True) 
    weight          = models.FloatField(blank = True, null = True)
    tradability     = models.CharField(max_length = 5,default=None, blank=True, null=True) 
    type            = models.CharField(max_length = 15,default=None, blank=True, null=True, db_index=True) 
    grade           = models.IntegerField(default=0, blank=True, null=True, db_index=True)
    icon            = models.CharField(max_length = 100,default=None, blank=True, null=True)
    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)
    def get_absolute_url(self):
        return reverse('Items:item', args=[str(self.ids)])
    def compare(self, their):
        if (
            self.ids == their.ids and 
            self.id_name == their.id_name and 
            self.cooldown == their.cooldown and 
            self.name == their.name and 
            self.weight == their.weight and 
            self.tradability == their.tradability and 
            self.type == their.type and 
            self.grade == their.grade and 
            self.icon == their.icon 
            ):
            return True 
        else:
            return False

   


class Equipments (models.Model):
    item            = models.OneToOneField(
                        Items,
                        on_delete=models.CASCADE,
                        primary_key=True,
                    )
    anvil_atk       = ListCharField(base_field=models.IntegerField(),
                    size=41,
                    max_length=(10 * 41),blank=True, null=True
                    )
    anvil_def       = ListCharField(base_field=models.IntegerField(),
                    size=41,
                    max_length=(10 * 41),blank=True, null=True
                    )
    anvil_price     = ListCharField(base_field=models.IntegerField(),
                    size=41,
                    max_length=(10 * 41),blank=True, null=True
                    )
    durability      = models.IntegerField(blank=True, null=True )
    level           = models.IntegerField(blank=True, null=True )
    potential       = models.IntegerField(blank=True, null=True )
    requiredClass   = models.CharField(max_length=10,default=None, blank=True, null=True )
    sockets_limit   = models.IntegerField(blank=True, null=True )
    stars           = models.IntegerField(blank=True, null=True )
    matk            = models.IntegerField(blank=True, null=True )
    patk            = models.IntegerField(blank=True, null=True )
    patk_max        = models.IntegerField(blank=True, null=True )
    mdef            = models.IntegerField(blank=True, null=True )
    pdef            = models.IntegerField(blank=True, null=True )
    transcend_price = ListCharField(base_field=models.IntegerField(),
                    size=10,
                    max_length=(3 * 10),
                    )
    type_attack     = models.CharField(max_length=20,default=None, blank=True, null=True)
    type_equipment  = models.CharField(max_length=20,default=None, blank=True, null=True)
    unidentified    = models.BooleanField()
    unidentifiedRandom = models.BooleanField()

    def is_goddess_armor(self):
        return self.item.grade ==6 and  self.type_equipment in ['Shirt', 'Pants', 'Boots', 'Gloves']


class Equipment_Bonus(models.Model):
    equipment =  models.ForeignKey(Equipments, 
        verbose_name="Equipment_Bonus", on_delete=models.CASCADE, )
    bonus_stat = models.CharField(max_length=30)
    bonus_val = models.TextField()
    def sepparateline(self):
        a =  self.bonus_val
        b = []
        for i in a :
            i.strip()
            if len(i) >0: 
                b.append(i)
        return a

class Cards (models.Model):
    item            = models.OneToOneField(
                        Items,
                        on_delete=models.CASCADE,
                        primary_key=True,
                    ) 
    type_card       = models.CharField(max_length=50,default=None, blank=True, null=True )
    icon            = models.CharField(max_length = 70,default=None, blank=True, null=True)


    def compare(self, their):
        if (
            self.item == their.item and 
            self.type_card == their.type_card and 
            self.icon == their.icon  
            ):
            return True 
        else:
            return False

class Gems (models.Model):
    item            = models.OneToOneField(
                        Items,
                        on_delete=models.CASCADE,
                        primary_key=True,
                    )
    skill           = models.ForeignKey(Skills, on_delete=models.CASCADE, null = True, blank = True, default = None)

    def compare(self, their):
        if (
            self.item == their.item and 
            self.skill == their.skill  
            ):
            return True 
        else:
            return False


class Recipes(models.Model):
    item            = models.OneToOneField(
                        Items,
                        on_delete=models.CASCADE,
                        primary_key=True,
                    )
    def compare(self, their):
        if (
            self.item == their.item  
            ):
            return True 
        else:
            return False


class Item_Recipe_Material(models.Model):
    recipe          =   models.ForeignKey(Recipes, 
        verbose_name="recipe", on_delete=models.CASCADE, )          
    material        = models.ForeignKey(Items, 
        verbose_name="recipe_material", on_delete=models.CASCADE, ) 
    qty             = models.IntegerField()

    def compare(self, their):
        if (
            self.recipe == their.recipe and 
            self.material == their.material and 
            self.qty == their.qty  
            ):
            return True 
        else:
            return False


class Item_Recipe_Target(models.Model):
    recipe          =   models.ForeignKey(Recipes, 
        verbose_name="recipe", on_delete=models.CASCADE, )          
    target          =  models.ForeignKey(Items, 
        verbose_name="target", on_delete=models.CASCADE)
    def compare(self, their):
        if (
            self.recipe == their.recipe and 
            self.target == their.target 
            ):
            return True 
        else:
            return False


class Cubes(models.Model):
    item            = models.OneToOneField(
                        Items,
                        on_delete=models.CASCADE,
                        primary_key=True,
                    )


class Collections(models.Model):
    item            = models.OneToOneField(
                        Items,
                        on_delete=models.CASCADE,
                        primary_key=True,
                    )


class Item_Collection_Material(models.Model):
    collection = models.ForeignKey(Collections, 
        verbose_name="collection", on_delete=models.CASCADE, )  
    material = models.ForeignKey(Items, 
        verbose_name="collection_material", on_delete=models.CASCADE, ) 

class Item_Collection_Bonus(models.Model):
    collection = models.ForeignKey(Collections, 
        verbose_name="collection", on_delete=models.CASCADE, )  
    bonus_stat = models.CharField(max_length=30)
    bonus_val = models.CharField(max_length=30)

class Item_Type(models.Model):
    name = models.CharField(max_length=30)
    is_equipment = models.BooleanField(default=False)

class Books(models.Model):
    item            = models.OneToOneField(
                        Items,
                        on_delete=models.CASCADE,
                        primary_key=True,
                    )
    text            = models.TextField( null = True, blank = True, default = None)


class Equipment_Set(models.Model):
    equipment   = models.ManyToManyField(Equipments)
    ids         = models.CharField(max_length = 30, db_index=True)
    id_name     = models.CharField(max_length = 30, db_index=True)
    name        =  models.CharField(max_length = 50, blank = True, default = None, null = True)
    bonus2      = models.CharField(max_length = 100, blank = True, default = None, null = True)
    bonus3      = models.CharField(max_length = 100, blank = True, default = None, null = True)
    bonus4      = models.CharField(max_length = 100, blank = True, default = None, null = True)
    bonus5      = models.CharField(max_length = 100, blank = True, default = None, null = True)
    bonus6      = models.CharField(max_length = 100, blank = True, default = None, null = True)
    bonus7      = models.CharField(max_length = 100, blank = True, default = None, null = True)
    def compare(self, their):
        if (
            self.equipment == their.equipment and 
            self.ids == their.ids and 
            self.id_name == their.id_name and 
            self.name == their.name and 
            self.bonus2 == their.bonus2 and 
            self.bonus3 == their.bonus3 and 
            self.bonus4 == their.bonus4 and 
            self.bonus5 == their.bonus5 and 
            self.bonus6 == their.bonus6 and 
            self.bonus7 == their.bonus7
            ):
            return True 
        else:
            return False

TavernofSoul/Market/models.py
from django.db import models
# from Skills.models import Equipments

class Crawl_Info(models.Model):
    crawl_uuid      = models.CharField(max_length = 40)
    serverid        = models.IntegerField(db_index=True)
    created         = models.DateTimeField(auto_now_add=True)
    def Goods(self):
        return self.goods_set.all()

class Goods(models.Model):
    items           = models.ForeignKey('Items.Items', db_index=True, on_delete=models.CASCADE)
    number          = models.IntegerField()
    price           = models.IntegerField()
    crawl_info      = models.ForeignKey(Crawl_Info, db_index=True, on_delete=models.CASCADE)
    uid             = models.CharField(max_length=20)
    def Option(self):
        return self.goods_option_set.all()


class Goods_Option(models.Model):
    goods           = models.ForeignKey(Goods,db_index=True,  on_delete=models.CASCADE)
    optionType      = models.TextField()
    optionValue     = models.IntegerField()

class Crawl_Summary(models.Model):
    date            = models.DateField(auto_now_add = True, db_index=True)
    serverid        = models.IntegerField(db_index= True)
    updated         = models.DateTimeField(auto_now=True)
    def Goods(self):
        return self.goods_summary_set.all()

class Goods_Summary(models.Model):
    items           = models.ForeignKey('Items.Items', db_index=True, on_delete=models.CASCADE)
    number          = models.IntegerField()
    price           = models.IntegerField()
    high            = models.IntegerField()
    low             = models.IntegerField()
    crawl_summary   = models.ForeignKey(Crawl_Summary, db_index=True, on_delete=models.CASCADE)
    def Option(self):
        return self.goods_option_set.all()

    

TavernofSoul/templates/Items/3dmodel.html
{%load static%}
<script src="https://unpkg.com/three@0.128.0/build/three.min.js"></script>
<script src="https://unpkg.com/three@0.128.0/examples/js/loaders/ColladaLoader.js"></script>
<script type="text/javascript">
	name 		= '{{item.equipments.model}}'
	path  		= '/static/models/{{item.equipments.model}}'
	name_dae 	= name + '.dae'
	name_dds 	= name + '.dds'
	container 	= $("#container_3d")[0]
	
	var scene 	= new THREE.Scene();
    var camera 	= new THREE.PerspectiveCamera( 75, window.innerWidth /     window.innerHeight, 0.1, 1000 );
    var renderer = new THREE.WebGLRenderer();

    renderer.setSize( window.innerWidth, window.innerHeight );
    container.appendChild( renderer.domElement );

    loader = new THREE.ColladaLoader();
    loader.load(path+'/'+name_dae,function colladaReady( collada ){
	    player = collada.scene;
	    scene.add( player );
    });

    camera.position.z = 5;

    function render() {
        requestAnimationFrame(render);
        renderer.render(scene, camera);

        //cube.rotation.x += 0.1;
        //cube.rotation.y += 0.1;
    }
    render();


</script>

TavernofSoul/templates/Items/collectionBonus.html
<br>
	  <table class="table-bordered border border-white border-responsive mt-1 tabe">
	    <tbody>
	    	{%for bonus in collectionBonus%}
		    	 <tr>
		    			<th>{{bonus.bonus_stat}}</th>
		    			<td>{{bonus.bonus_val}}</td>
		      </tr>
	      {%endfor%}
	    </tbody>
	 
	  </table>

TavernofSoul/templates/Items/enhancement.html
{% load translate%}
{% load static%}
	  <h2>Enhancement</h2>
	  <div class="form-inline">
		  <table class="table-bordered border border-white border-responsive mt-1 mr-2 tabe  text-center">
		  	<thead>
		      <tr>
		      	<th >{{"Anvil" | translate}}</th>
		      	<th >{{"Bonus" | translate}}</th>
		      	{%if item.grade == 6%}
		      		{%for key, values in mat.30.items%}
  				        	<th ><a href='{{values.mat_ids}}'><img class="icon-24" src="/static/icons/{{ values.mat_icon }}.png" title="{{values.mat_name}}" alt="{{values.mat_name}}"></a></th>
			        {%endfor%}
			        <th>{{"Chance" | translate}}</th>
		      	{%else%}
			        <!-- <th >{{"Price" | translate}}</th> -->
			        <th >{{"Cost" | translate}}</th>
		        	<th >{{"Total" | translate}}</th>
		        {%endif%}
		      </tr>
		    </thead>
		    <tbody style="text-align:center">
		    	<tr>
		      	<td ><input class="form-control-sm " type='text'
		      		id="anvil" style="width :40px"></td>
		      	<td id = 'anvil_bonus' ></td>
		      	{%if item.grade == 6%}
		      		{%for key, values in mat.30.items%}
  				        <td id = '{{key}}' ></td>
			        {%endfor%}
			        <td id = 'chance_ench'></td>
		      	{%else%}
		        <td id = 'anvil_price' ></td>
	        	<td id = 'anvil_total'></td>
	        	{%endif%}
		      </tr>
		    </tbody>
		 
		  </table>

		  <br>
		  {% if tc_cost%}
		  <table class="table-bordered border border-white border-responsive mt-1 tabe text-center">
		  	<thead>
		      <tr>
		      	<th >{{"TC" | translate}}</th>
		      	<th >{{"Bonus" | translate}}</th>
		        <th >{{"BG" | translate}}</th>
	        	<th >{{"Total" | translate}}</th>
		      </tr>
		    </thead>
		    <tbody style="text-align:center" >
		    	<tr>
		      	<td ><input class="form-control-sm "  type='text'
		      		id="tc" style="width :40px; text-align: center;"></td>
		      	<td id = 'tc_bonus' ></td>
		        <td id = 'tc_price' ></td>
		        <td id = 'tc_total' ></td>
		      </tr>
		    </tbody>
		 
		  </table>
		  {%endif%}
		</div>
	 

TavernofSoul/templates/Items/equipment_bonus.html
 <br>
	  <table class="table-bordered border border-white border-responsive mt-1 tabe">
	    <tbody>
	    	{%for bonus in equipment_bonus%}
	    	 <tr>
	    			<th>{{bonus.bonus_stat}}</th>

	    			<td>
	    		            {%for b in bonus.bonus_val %}
                                     {{b}}<br> {%endfor%}
	    					
	    			</td>
	      </tr>
	      {%endfor%}
	    </tbody>
	 
	  </table>

TavernofSoul/templates/Items/equipment_set.html
{% load translate%}
{% load static%}
{%load utils%}
<br>
	  <h2>Equipment Set</h2>
	  {%for set in item.equipments.equipment_set_set.all %}
		   <div class="form-inline">
			    <table class="table-bordered border border-white border-responsive mt-1 mr-2 tabe">
		    	    <tbody>
				    	<tr>
				    		<th>{{"Set Name" | translate}} </th>
			    			<th>{{set.name}}</th>
			    		</tr>
		    			{%if set.bonus2%}
		    			<tr>
		    				<th>-</th>
		    				<td>{{set.bonus2 | stringFormat }}</td>
		    			</tr>
		    			{%endif%}
		    			{%if set.bonus3%}
		    			<tr>
		    				<th>-</th>
		    				<td>{{set.bonus3 | stringFormat }}</td>
	    				</tr>
		    			{%endif%}
		    			{%if set.bonus4%}
		    			<tr>
		    				<th>-</th>
		    				<td>{{set.bonus4 | stringFormat }}</td>
		    			</tr>
		    			{%endif%}
		    			{%if set.bonus5%}
		    			<tr>
		    				<th>-</th>
		    				<td>{{set.bonus5 | stringFormat }}</td>
		    			</tr>
		    			{%endif%}
		    			{%if set.bonus6%}
		    			<tr>
		    				<th>-</th>
		    				<td>{{set.bonus6 | stringFormat }}</td>
		    			</tr>
		    			{%endif%}
		    			{%if set.bonus7%}
		    			<tr>
		    				<th>-</th>
		    				<td>{{set.bonus7 | stringFormat }}</td>
		    			</tr>
		    			{%endif%}
		    			<tr>
		    				<th>{{"Sets" | translate}}</th>
		    				<td>
		    				{%for link in set.equipment.all%}
		    					<img loading="lazy" alt="" src="/static/icons/{{link.item.icon}}.png") class="icon-24"> 	<a href="{{link.item.ids}}">{{link.item.name}}</a>
		    						<br>
		    				{%endfor%}
		    				</td>
		    			</tr>
				    </tbody>
    			</table>
			</div>
		{%endfor%}

TavernofSoul/templates/Items/market.html
 {% load translate%}
 {% load utils%}
 <br>
<h2>{{"Market" | translate}}</h2>
<table class="table-bordered border border-white border-responsive mt-1 tabe">
<tbody>
	<tr>
		<th rowspan="2">{{'Date' | translate}}</th>
		<th rowspan="2">{{'Server' | translate}}</th>
		<th rowspan="2">{{'Total Number' | translate}}</th>
		<th rowspan="1" colspan="3">{{'Price' | translate}}</th>
	</tr>
	<tr>
		<th>{{'low' | translate}}</th>
		<th>{{'avg' | translate}}</th>
		<th>{{'hi' | translate}}</th>
  </tr>
	{%for goods in item.Goods%}
	 <tr>
		<td>{{goods.crawl_summary.date}}</td>
		<td>{{goods.crawl_summary.serverid | translateServer }}</td>
		<td class="text-align-right">{{goods.number | intspace }}</td>
		<td class="text-align-right">{{goods.low 	| intspace }}</td>
		<td class="text-align-right">{{goods.price 	| intspace }}</td>
		<td class="text-align-right">{{goods.high 	| intspace }}</td>
  </tr>
  {%endfor%}
</tbody>

</table>

TavernofSoul/templates/Items/materials.html
{% load translate%}
	<br>
	<h2>{{"Materials" | translate}}</h2>
	  <table class="table-bordered border border-white border-responsive mt-1 tabe">
	    <tbody>
	    	{%for material in collectionMaterial%}
	    	 <tr>
	    		<td><img loading="lazy" alt="" src="/static/icons/{{material.material.icon}}.png") class="icon-24"> 	<a href="{{material.material.ids}}">{{material.material.name}}</a></td>
	      </tr>
	      {%endfor%}
	    </tbody>
	 
	  </table>

TavernofSoul/templates/Items/recipes.html
{% load translate%}
<br>
	<h2>{{"Produce" | translate}}</h2>
	<table class="table-bordered border border-white border-responsive mt-1 tabe">
		<tbody>
			{% for i in target%}
			<tr>
				<td>
					<img loading="lazy" alt="" src="/static/icons/{{i.target.icon}}.png") class="icon-32">
				</td>
				<td>
					<a href="{{i.target.ids}}">{{i.target.name}}</a>
				</td>
			</tr>
			{%endfor%}
		</tbody>
	</table>
	<br>
	<h2>{{"Materials" | translate}}</h2>
	<table class="table-bordered border border-white border-responsive mt-1 tabe">
		<tbody>
			{% for i in materialRecipe%}
			<tr>
				<td>
					<img loading="lazy" alt="" src="/static/icons/{{i.material.icon}}.png") class="icon-32">
				</td>
				<td>
					<a href="{{i.material.ids}}">{{i.material.name}}</a>
				</td>
				<td style="text-align:right;">
					x{{i.qty}}
				</td>
			</tr>
			{%endfor%}
		</tbody>
	</table>

TavernofSoul/templates/Items/refferences.html
{% load translate%}
  <h2>{{"Refferences" | translate}}</h2>
  
  	<table class="table-bordered border border-white border-responsive mt-1 tabe">
		    <tbody>
		    	{%if targetRecipe%}
		    	<tr>
		      	<th>{{"Crafted From" | translate}}</th>
		      	<td>
		      		{%for i in targetRecipe%}
		      			<a href="{{i.recipe.item.ids}}"> <p class="mb-0"> <img loading="lazy" alt="" src="/static/icons/{{i.recipe.item.icon}}.png") class="icon-24">{{i.recipe.item.name}}</p></a>
		      			
		      		{%endfor%}
		      	</td>
		      </tr>
		      {%endif%}

		      {%if collectionMaterialFor%}
		      <tr>
		      	<th>{{"Collections" | translate}}</th>
		      	<td>
			      	{%for i in collectionMaterialFor%}
		      			<a href="{{i.collection.item.ids}}"><p class="mb-0"><img loading="lazy" alt="" src="/static/icons/{{i.collection.item.icon}}.png") class="icon-24"> {{i.collection.item.name}}</p></a>
			      			
		      		{%endfor%}
	      		</td>
		      </tr>
		      {% endif %}
		      {%if dropped%}
		    	<tr>
		      	<th style="vertical-align:top">{{"Dropped by" | translate}}</th>
		      	<td>
		      		{%for i in dropped%}
		      			<p class="mb-0"> <a href="{%url 'Monsters:monster' i.monster.ids%}"> <img loading="lazy" alt="" src="/static/icons/{{i.monster.icon}}.png") class="icon-24">{{i.monster.name}}</a> ({{i.chance}} %)</p> 
		      			
		      		{%endfor%}
		      	</td>
		      </tr>
		      {%endif%}
		      {%if mapDrop%}
		      <th style="vertical-align:top">{{"Dropped at" | translate}}</th>
		      	<td>
		      		{%for i in mapDrop%}
		      			<p class="mb-0"> <a href="{%url 'Maps:maps' i.map.ids%}"> {{i.map.name}}</a> ({{i.chance}} %)</p> 
		      			
		      		{%endfor%}
		      	</td>
		      </tr>
		      {%endif%}
		    </tbody>
		 
		  </table>