TavernofSoul/Dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

TavernofSoul/Items/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:id>', views.item_detail, name='item'),
]

TavernofSoul/Jobs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.item_detail, name='jobs'),
]

TavernofSoul/Maps/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:id>', views.item_detail, name='maps'),
]

TavernofSoul/Monsters/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.item_detail, name='monster'),
]

TavernofSoul/Skills/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.item_detail, name='skills'),
]

TavernofSoul/TavernofSoul/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap # new
from Attributes.models import Attributes
from Buffs.models import Buffs
from Items.models import Items
from Jobs.models import Jobs
from Skills.models import Skills
from Maps.models import Maps
from django.contrib.sitemaps import Sitemap
from django.shortcuts import reverse
class StaticViewSitemap(Sitemap):
    def items(self):
        return ['Dashboard:index', 
            'Items:index', 
            'Skills:index', 
            'Buffs:index', 
            'Jobs:index',
            'Attributes:index',
            'Planner:index',
            'Other:achieve'
            ]
    def location(self, item):
        return reverse(item)

sitemaps = {
    'static'     : StaticViewSitemap,
    "attributes" : GenericSitemap({'queryset' : Attributes.objects.all()}),
    "buffs"      : GenericSitemap({'queryset' : Buffs.objects.all()}),
    "items"      : GenericSitemap({'queryset' : Items.objects.all()}),
    "jobs"       : GenericSitemap({'queryset' : Jobs.objects.all()}),
    "maps"       : GenericSitemap({'queryset' : Maps.objects.all()}),
    "skills"     : GenericSitemap({'queryset' : Skills.objects.all()}),


}

urlpatterns = [
    path('', include(('Dashboard.urls',"Dashboard"),namespace = "Dashboard")),    
    path('items/', include(('Items.urls',"Items"),namespace = "Items")),   
    path('monsters/', include(('Monsters.urls',"Monsters"),namespace = "Monsters")), 
    path('maps/', include(('Maps.urls',"Maps"),namespace = "Maps")), 
    path('jobs/', include(('Jobs.urls',"Jobs"),namespace = "Jobs")), 
    path('skills/', include(('Skills.urls',"Skills"),namespace = "Skills")), 
    path('attributes/', include(('Attributes.urls',"Attributes"),namespace = "Attributes")), 
    path('buffs/', include(('Buffs.urls',"Buffs"),namespace = "Buffs")), 
    path('planner/', include(('Planner.urls',"Planner"),namespace = "Planner")), 
    path('other/', include(('Other.urls',"Other"),namespace = "Other")), 
    #path('changes/', include(('ipfparser.urls',"Parser"),namespace = "Parser")), 
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TavernofSoul/Dashboard/models.py
from django.db import models

# Create your models here.


class Version (models.Model):
	version 	 	= models.CharField(max_length=50)
	created 		= models.DateTimeField(auto_now_add=True)

TavernofSoul/Dashboard/views.py
from django.shortcuts import render
from os.path import join
from Items.models import Items
from Monsters.models import Monsters 
from Jobs.models import Jobs
from Skills.models import Skills
from Attributes.models import Attributes 
from Maps.models import Maps
from Dashboard.models import Version

# Create your views here.
APP_NAME = "Dashboard"

def index(request):

	FUNCT_NAME = 'index'
	if 'q' in request.GET:
		query = request.GET['q']
		data = {}
		data['item'] = list(Items.objects.filter(name__icontains = query))
		data['item_len'] = len(data['item'])
		data['item'] = data['item'] [:5]

		data['monster'] = list(Monsters.objects.filter(name__icontains = query))
		data['monster_len'] = len(data['monster'])
		data['monster'] = data['monster'] [:5]
		data['query'] = query

		data['maps'] = list(Maps.objects.filter(name__icontains=query))
		data['maps_len'] = len(data['maps'])
		data['maps'] = data['maps'][:5]

		data['jobs'] = list(Jobs.objects.filter(name__icontains=query))
		data['jobs_len'] = len(data['jobs'])
		data['jobs'] = data['jobs'][:5]

		att = list(Attributes.objects.filter(name__icontains=query))

		
		data['attributes_len'] = len(att)
		data['attributes'] = []
		for i in att[:5]:
			i.descriptions = i.descriptions.split("{nl}")
			data['attributes'].append(i)

		data['skills'] = list(Skills.objects.filter(name__icontains=query))
		data['skills_len'] = len(data['skills'])
		data['skills'] = data['skills'][:5]

		return render(request, join(APP_NAME,"search.html"), data)	
	else:
		ver = Version.objects.latest('created')
		context = {"version" : ver.version}
		return render(request, join(APP_NAME,"index.html"), context)

TavernofSoul/templates/Dashboard/index.html
{% extends 'base/index.html' %}
{%block head%}
    <title>Tavern of Soul</title>
    
    <meta content="Tavern of Soul" property="og:title" />
    <meta content="Tree of Savior database" property="og:description" />
    <meta name="description" content="Tree of Savior database">
    <meta content="https://itos.tavernofsoul.com" property="og:url" />
    <meta content="https://itos.tavernofsoul.com/static/images/logo.png" property="og:image" />
    <meta content="#43B581" data-react-helmet="true" name="theme-color" />

{%endblock%}
<!--Block content goes below-->


  {% block content %}

<div class="d-flex align-items-center container "  style="height: 100%;">
  <div class="row  justify-content-center" style=" width:100%;
    height: 100px;
    text-align: center;
    vertical-align: middle;
    top: 50%;
    margin-top: -50px;
    "> 
    
  <form class="form-inline justify-content-center"  style="width: 100%;"autocomplete="off" action="/" method="GET">
 
      <input type="input" class="form-control col-md-6" id="inputPassword2" placeholder="Search..."  name="q" >
 
</form>
  </div>
  <div class="row mr-2" style="position: fixed;
      bottom: 0;
      right:0px;
      color:#babbbf;
  ">
    Version : {{version}}
  </div>
</div>
  {% endblock %}

TavernofSoul/templates/Dashboard/search.html
{% extends 'base/index.html' %}
{%load translate%}
{%block head%}
    <title>Tavern of Soul</title>
    <meta content="Tavern of Soul" property="og:title" />
    <meta content="Tree of Savior database" property="og:description" />
    <meta name="description" content="Tree of Savior database">
    <meta content="https://itos.tavernofsoul.com" property="og:url" />
    <meta content="https://itos.tavernofsoul.com/static/images/logo.png" property="og:image" />
    <meta content="#43B581" data-react-helmet="true" {{"Name" | translate}}="theme-color" />

{%endblock%}
<!--Block content goes below-->


  {% block content %}

<h1 id="title">{{"Results"|translate}}"</h1>
<form autocomplete="off" action="/" method="GET" class="form-inline">
  <input  class="form-control" type="text" required="" {{"Name" | translate}}="q" value="{{query}}">
</form>
<br>

{% if item%}
  <h2>{{"Items" | translate}}</h2>
  <label class="mt-1 mb-1">{{item_len}} {{"Results"|translate}}</label>
  <div class="o-wrap">
  <table class="table-bordered border border-white border-responsive">
    <thead>
      <tr>
        <th></th>
        <th>ClassID</th>
        <th>{{"Name" | translate}}</th>
        <th>{{"Type" | translate}}</th>
        <th>{{"Grade" | translate}}</th>
        <th>{{"Level" | translate}}</th>
      </tr>
    </thead>
    <tbody>
      {% for i in item %}
      <tr>
        <td><img loading="lazy" alt="" src="static/icons/{{i.icon}}.png") class="icon-64"></td>
        <td><a href="{%url 'Items:item' i.ids%}">{{i.ids}}</a></td>
        <td>{{i.name}}</td>
        {%if i.equipments %}
        <td>{{i.equipments.type_equipment}}</td>
        {%else%}
        <td>{{i.type}}</td>
        {% endif %}
        {%if i.grade%}
          <td class="cell-center"><span class="item-grade item-grade-{{i.grade}}"></span></td>
        {%else%}
          <td></td>
        {%endif%}
        <td>{{i.equipments.level}}</td>
      </tr>
      
       
      {%endfor%}
    </tbody>
    {%if item_len >= 5%}
    <tfoot>
      <tr>
        <td class="footer-more" colspan="6">
          <a href="/items?q={{query}}"}>{{item_len}} {{"more" | translate}}</a>
        </td>
      </tr>
    </tfoot>
    {% endif %}
  </table>

  </div>
{%endif%}


{% if monster%}
  <h2>{{"NPCs" | translate}}</h2>

  <label class="mt-1 mb-1">{{monster_len}} {{"Results"|translate}}</label>
  <table class="table-bordered border border-white border-responsive mt-1 ">
    <thead>
      <tr>
        <th>ClassID</th>
        <th>{{"Name" | translate}}</th>
        <th>{{"Level" | translate}}</th>
        <th>{{"Race" | translate}}</th>
        <th>{{"Elements" | translate}}</th>
        <th>{{"Armor" | translate}}</th>
        <th>ClassName</th>
      </tr>
    </thead>
    <tbody>
      {% for i in monster %}
      <tr>
        <td><a href="{%url 'Monsters:monster' i.ids %}">{{i.ids}}</a></td>
        <td>{{i.name}}</td>
        <td>{{i.level}}</td>
        <td>{{i.race}}</td>
        <td>{{i.element}}</td>
        <td>{{i.armor}}</td>
        <td>{{i.id_name}}</td>
      </tr>
      
       
      {%endfor%}
    </tbody>
    {%if monster_len >= 5%}
    <tfoot>
      <tr>
        <td class="footer-more" colspan="7">
          <a href="/monsters?q={{query}}"}>{{monster_len}} {{"more" | translate}}</a>
        </td>
      </tr>
    </tfoot>
    {% endif %}
  </table>
{%endif%}



{% if maps%}
  <h2>{{"Maps" | translate}}</h2>

  <label class="mt-1 mb-1">{{maps_len}} {{"Results"|translate}}</label>
  <table class="table-bordered border border-white border-responsive mt-1 ">
    <thead>
      <tr>
        <th>ClassID</th>
        <th>ClassName</th>
        <th>{{"Name" | translate}}</th>
        <th>{{"Level" | translate}}</th>
        <th>{{"Type" | translate}}</th>
      </tr>
    </thead>
    <tbody>
      {% for i in maps %}
      <tr>
        <td><a href="{%url 'Maps:maps' i.ids %}">{{i.ids}}</a></td>
        <td>{{i.name}}</td>
        <td>{{i.id_name}}</td>
        <td>{{i.level}}</td>
        <td>{{i.type}}</td>
      </tr>
      
       
      {%endfor%}
    </tbody>
    {%if maps_len >= 5%}
    <tfoot>
      <tr>
        <td class="footer-more" colspan="7">
          <a href="/monsters?q={{query}}"}>{{maps_len}} {{"more" | translate}}</a>
        </td>
      </tr>
    </tfoot>
    {% endif %}
  </table>
{%endif%}




{% if jobs%}
  <h2>{{"Jobs" | translate}}</h2>

  <label class="mt-1 mb-1">{{jobs_len}} {{"Results"|translate}}</label>
  <table class="table-bordered border border-white border-responsive mt-1 ">
    <thead>
      <tr>
        <th></th>
        <th>ClassID</th>
        <th>ClassName</th>
        <th>{{"Class Tree" | translate}}</th>
        <th>{{"Name" | translate}}</th>
      </tr>
    </thead>
    <tbody>
      {% for i in jobs %}
      <tr>
        <td><img loading="lazy" alt="" src="/static/icons/{{i.icon}}.png") class="icon-64"></td>
        <td><a href="{%url 'Jobs:jobs' i.ids %}">{{i.ids}}</a></td>
        <td>{{i.id_name}}</td>
        <td>{{i.job_tree}}</td>
        <td>{{i.name}}</td>
      </tr>
      
       
      {%endfor%}
    </tbody>
    {%if jobs_len >= 5%}
    <tfoot>
      <tr>
        <td class="footer-more" colspan="7">
          <a href="/monsters?q={{query}}"}>{{jobs_len}} {{"more" | translate}}</a>
        </td>
      </tr>
    </tfoot>
    {% endif %}
  </table>
{%endif%}



{% if skills%}
  <h2>{{"Skills" | translate}}</h2>

  <label class="mt-1 mb-1">{{skills_len}} {{"Results"|translate}}</label>
  <table class="table-bordered border border-white border-responsive mt-1 ">
    <thead>
     <tr>
        <th></th>
        <th>ClassID</th>
        <th>{{"Name" | translate}}</th>
        <th>{{"Job" | translate}}</th>
        <th>{{"Max Level" | translate}}</th>

      </tr>
    </thead>
    <tbody>
      {% for i in skills %}
      <tr>
        <td><img loading="lazy" alt="" src="/static/icons/{{i.icon}}.png") class="icon-64"></td>
        <td><a href="{%url 'Skills:skills' i.ids %}">{{i.ids}}</a></td>
        <td>{{i.name}}</td>
        <td>{{i.job.name}}</td>
        <td>{{i.max_lv}}</td>
      </tr>
       
      {%endfor%}
    </tbody>
    {%if skills_len >= 5%}
    <tfoot>
      <tr>
        <td class="footer-more" colspan="7">
          <a href="/monsters?q={{query}}"}>{{skills_len}} {{"more" | translate}}</a>
        </td>
      </tr>
    </tfoot>
    {% endif %}
  </table>
{%endif%}




{% if attributes%}
  <h2>{{"Attribute" | translate}}</h2>

  <label class="mt-1 mb-1">{{attributes_len}} {{"Results"|translate}}</label>
  <table class="table-bordered border border-white border-responsive mt-1 ">
    <thead>
      <tr>
        <th></th>
        <th>ClassID</th>
        <th>ClassName</th>
        <th>{{"Name" | translate}}</th>
        <th>{{"Description" | translate}}</th>
        <th>{{"Max Level" | translate}}</th>
      </tr>
    </thead>
    <tbody>
      {% for i in attributes %}
      <tr>
        <td><img loading="lazy" alt="" src="/static/icons/{{i.icon}}.png") class="icon-64"></td>
        <td><a href="{%url 'Attributes:attributes' i.ids %}">{{i.ids}}</a></td>
        <td>{{i.id_name}}</td>
        <td>{{i.name}}</td>
        <td>
        {% for lines in i.descriptions %}
            <p class="mb-1">{{lines}}</p>
        {%endfor%}
        </td>
        <td>{{i.max_lv}}</td>
      </tr>
      
       
      {%endfor%}
    </tbody>
    {%if attributes_len >= 5%}
    <tfoot>
      <tr>
        <td class="footer-more" colspan="7">
          <a href="/monsters?q={{query}}"}>{{attributes_len}} {{"more" | translate}}</a>
        </td>
      </tr>
    </tfoot>
    {% endif %}
  </table>
{%endif%}





  {% endblock %}